### ISSUE TITLE
New line and spaces with animation works!!!

### ISSUE THREAD

**Issue by sidshekar** [SteveBarnegren/CCLabelBMFontAnimated#1]
Thanks for the help. I still extend CCLabelBMFont but expose _Lable and _CurrentUTF and check for if character at index is != '/n'

![testanimtypewriter](https://cloud.githubusercontent.com/assets/2862097/6913239/16aec878-d79b-11e4-8e49-9fc1b267b584.gif)

**Comment by Cephiros** [comment]
I cant figure out how to get this to work, how did you do this?

**Comment by sidshekar** [comment]
You can get the modified class from here:
https://www.dropbox.com/s/p3a6gboh2rmjlcj/CClabelBMFontAnimated_modified_sid.zip?dl=0

NOTE: You will still need to expose _Label abd _CurrentUTF variables in the Label class. Just make it public.

# Usage

CCLabelBMFontAnimated\* label = CCLabelBMFontAnimated::create("","Fonts/mtCastleSign.fnt", 400, TextHAlignment::CENTER);
    label->setPosition(Vec2(this->getContentSize().width/2, this->getContentSize().height/2 + this->getContentSize().height));

this->addChild(label);

label->setString("Hey!! \n This Totally Works \n v1.0 ");
label->animateInTypewriter(1.0);

NOTE: this only works witg typewriter animation. For other change the animation function accordingly.

**Comment by Cephiros** [comment]
EXCELLENT! i was heading in the right direction but i was working down the wrong path.i was trying to check for /n using just _currentUTF16String, not the _label route. thank you very much for the help! and even moreso for the speed of the reply.

**Comment by sidshekar** [comment]
No problems. Glad I could help. :)
